# Generated by Django 5.2.13 on 2026-08-07 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_envoi']},
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], db_index=True, default='NORMALE', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('INFO', 'Information'), ('ALERTE', 'Alerte'), ('VALIDATION', 'Validation'), ('REFUS', 'Refus'), ('PAIE', 'Paie'), ('DOCUMENT', 'Document'), ('DEMANDE', 'Demande'), ('PLANNING', 'Planning'), ('POINTAGE', 'Pointage')], db_index=True, default='INFO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['salarie', 'is_read'], name='notificatio_salarie_03c109_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['salarie', 'type_notification'], name='notificatio_salarie_69c7bb_idx'),
        ),
    ]
