# Generated by Django 5.2.13 on 2026-05-02 14:41

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='matricule',
            field=models.CharField(default=apps.users.models.generate_matricule, max_length=50, unique=True),
        ),
    ]
