# Generated by Django 5.2.13 on 2026-08-07 00:35

import apps.users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salarie_must_change_password_alter_salarie_matricule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarie',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AlterField(
            model_name='salarie',
            name='email_personnel',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='matricule',
            field=models.CharField(db_index=True, default=apps.users.models.generate_matricule, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='role',
            field=models.CharField(choices=[('SALARIE', 'Salarié'), ('RH', 'Ressources humaines'), ('ADMIN', 'Administrateur')], db_index=True, default='SALARIE', max_length=10),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('VACATAIRE', 'Vacataire'), ('STAGIAIRE', 'Stagiaire'), ('ALTERNANT', 'Alternant')], db_index=True, default='CDI', max_length=30),
        ),
        migrations.AddIndex(
            model_name='salarie',
            index=models.Index(fields=['role', 'etablissement'], name='users_salar_role_c91015_idx'),
        ),
        migrations.AddIndex(
            model_name='salarie',
            index=models.Index(fields=['type_contrat', 'etablissement'], name='users_salar_type_co_405750_idx'),
        ),
    ]
