# Generated by Django 5.2.13 on 2026-08-10 02:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteCET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_heures', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salarie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_cet', to='users.salarie')),
            ],
            options={
                'ordering': ['salarie__nom', 'salarie__prenom'],
            },
        ),
    ]
