# Generated by Django 5.2.13 on 2026-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_comptecet'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salarie',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salarie',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salarie',
            name='nationalite',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salarie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profils/%Y/%m/'),
        ),
    ]
