# Generated by Django 5.1.2 on 2026-03-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('numero_secu', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(default='Paris', max_length=100)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('lien_familial', models.CharField(blank=True, max_length=50)),
                ('infos_complementaires', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='users.salarie')),
            ],
        ),
    ]
