# Generated by Django 5.2.13 on 2026-04-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('voie', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='EtatCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secu', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('salarie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(max_length=20)),
                ('titulaire', models.CharField(max_length=100)),
                ('salarie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.salarie')),
            ],
        ),
    ]
