# Generated by Django 5.2.13 on 2026-08-07 01:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_adresse_etatcivil_famille_iban'),
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='contact_nom',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='contact_telephone',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='lien_familial',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='numero_secu',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='etatcivil',
            name='nom',
        ),
        migrations.AddField(
            model_name='adresse',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adresse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adresse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='nationalite',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='nom_naissance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='nom_usage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='pays_naissance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='etatcivil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='famille',
            name='contact_urgence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='famille',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famille',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='famille',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iban',
            name='nom_banque',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='iban',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='salarie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adresse', to='users.salarie'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='infos_complementaires',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='etatcivil',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etatcivil',
            name='numero_secu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='etatcivil',
            name='salarie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_civil', to='users.salarie'),
        ),
        migrations.AlterField(
            model_name='etatcivil',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme'), ('AUTRE', 'Autre'), ('NR', 'Non renseigné')], default='NR', max_length=10),
        ),
        migrations.AlterField(
            model_name='famille',
            name='lien',
            field=models.CharField(choices=[('CONJOINT', 'Conjoint(e)'), ('ENFANT', 'Enfant'), ('PARENT', 'Parent'), ('FRERE_SOEUR', 'Frère ou sœur'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='famille',
            name='salarie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_famille', to='users.salarie'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='iban',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='iban',
            name='salarie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordonnees_bancaires', to='users.salarie'),
        ),
        migrations.AlterField(
            model_name='iban',
            name='titulaire',
            field=models.CharField(max_length=150),
        ),
    ]
