# Generated by Django 5.1.2 on 2026-03-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('heure_depart', models.TimeField()),
                ('heures_travaillees', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heures_sup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mois_paie', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='users.salarie')),
            ],
        ),
    ]
