# Generated by Django 5.2.13 on 2026-08-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointage',
            options={'ordering': ['-date', '-heure_arrivee']},
        ),
        migrations.AddField(
            model_name='pointage',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_sup',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_travaillees',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='mois_paie',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['salarie', 'date'], name='pointage_po_salarie_86619e_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['salarie', 'mois_paie'], name='pointage_po_salarie_3d72ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(fields=('salarie', 'date', 'heure_arrivee'), name='unique_pointage_salarie_date_arrivee'),
        ),
    ]
