# Generated by Django 5.1.2 on 2026-04-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('ACOMPTE', 'Acompte'), ('AVANCE', 'Avance'), ('CET', 'Paiement CET'), ('HEURES_SUP', 'Paiement heures sup')], max_length=50)),
                ('montant_souhaite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='users.salarie')),
            ],
        ),
    ]
