# Generated by Django 5.2.13 on 2026-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_demande',
            field=models.CharField(choices=[('ACOMPTE', 'Acompte'), ('AVANCE', 'Avance'), ('CET', 'Paiement CET'), ('HEURES_SUP', 'Paiement heures sup'), ('ABSENCE', 'Absence')], max_length=50),
        ),
    ]
