# Generated by Django 5.2.13 on 2026-08-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_alter_demande_statut_alter_demande_type_demande'),
        ('users', '0002_salarie_must_change_password_alter_salarie_matricule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demande',
            options={'ordering': ['-date_demande']},
        ),
        migrations.AddField(
            model_name='demande',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='demande',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='demandes/justificatifs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_demande',
            field=models.CharField(choices=[('ACOMPTE', 'Acompte'), ('AVANCE', 'Avance'), ('CALENDRIER', 'Modification du calendrier'), ('FICHE', 'Demande de fiche'), ('CET', 'Paiement CET'), ('HEURES_SUP', 'Paiement heures supplémentaires'), ('ABSENCE', 'Absence')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['salarie', 'statut'], name='demandes_de_salarie_3496bb_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['type_demande', 'statut'], name='demandes_de_type_de_db49a1_idx'),
        ),
    ]
