# Generated by Django 5.2.13 on 2026-08-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_alter_demande_options_demande_details_and_more'),
        ('pointage', '0002_alter_pointage_options_pointage_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='pointages',
            field=models.ManyToManyField(blank=True, related_name='demandes_heures_sup', to='pointage.pointage'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_demande',
            field=models.CharField(choices=[('ACOMPTE', 'Acompte'), ('AVANCE', 'Avance'), ('CALENDRIER', 'Modification du calendrier'), ('FICHE', 'Demande de fiche'), ('CET', 'Paiement CET'), ('HEURES_SUP', 'Paiement heures supplémentaires'), ('ABSENCE', 'Absence')], db_index=True, max_length=50),
        ),
    ]
