# Generated by Django 5.1.2 on 2026-04-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('SALAIRE', 'Salaire'), ('ACOMPTE', 'Acompte'), ('AVANCE', 'Avance'), ('CET', 'Paiement CET'), ('HEURES_SUP', 'Heures sup'), ('FICHE_PAIE', 'Fiche de paie'), ('CALENDRIER_PAIE', 'Calendrier de paie')], max_length=50)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_paiement', models.DateField()),
                ('preuve_pdf', models.FileField(blank=True, null=True, upload_to='paiements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='users.salarie')),
            ],
        ),
    ]
