# Generated by Django 5.2.13 on 2026-08-09 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_alter_demande_options_demande_details_and_more'),
        ('paie', '0001_initial'),
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paie',
            options={'ordering': ['-date_paiement', '-created_at']},
        ),
        migrations.AddField(
            model_name='paie',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paie',
            name='date_paiement',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='paie',
            name='demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='demandes.demande'),
        ),
        migrations.AlterField(
            model_name='paie',
            name='preuve_pdf',
            field=models.FileField(blank=True, null=True, upload_to='paiements/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='paie',
            name='type_paiement',
            field=models.CharField(choices=[('SALAIRE', 'Salaire'), ('ACOMPTE', 'Acompte'), ('AVANCE', 'Avance'), ('CET', 'Paiement CET'), ('HEURES_SUP', 'Heures supplémentaires'), ('FICHE_PAIE', 'Fiche de paie'), ('CALENDRIER_PAIE', 'Calendrier de paie')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='paie',
            index=models.Index(fields=['salarie', 'date_paiement'], name='paie_paie_salarie_85e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='paie',
            index=models.Index(fields=['type_paiement', 'date_paiement'], name='paie_paie_type_pa_21a464_idx'),
        ),
    ]
