# Generated by Django 5.2.13 on 2026-08-10 18:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_alter_paie_options_paie_commentaire_paie_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('libelle', models.CharField(max_length=150)),
                ('type_cotisation', models.CharField(choices=[('SANTE', 'Assurance santé'), ('ATMP', 'Accidents du travail'), ('RETRAITE', 'Assurance retraite'), ('RETRAITE_COMPLEMENTAIRE', 'Retraite complémentaire'), ('CHOMAGE', 'Assurance chômage'), ('CSG_CRDS', 'CSG / CRDS'), ('AUTRE', 'Autre cotisation')], db_index=True, default='AUTRE', max_length=40)),
                ('type_base', models.CharField(choices=[('BRUT', 'Salaire brut'), ('BRUT_ABATTU', 'Salaire brut abattu'), ('PLAFOND', 'Base plafonnée')], default='BRUT', max_length=30)),
                ('taux_salarial', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('taux_employeur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('date_debut', models.DateField(db_index=True)),
                ('date_fin', models.DateField(blank=True, db_index=True, null=True)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
                'indexes': [models.Index(fields=['code', 'actif'], name='paie_tauxco_code_47e68d_idx'), models.Index(fields=['type_cotisation', 'actif'], name='paie_tauxco_type_co_75feda_idx'), models.Index(fields=['date_debut', 'date_fin'], name='paie_tauxco_date_de_3af0f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'date_debut'), name='unique_taux_cotisation_code_date_debut')],
            },
        ),
    ]
