# Generated by Django 5.1.2 on 2026-04-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI', "Carte d'identité"), ('PASSPORT', 'Passeport'), ('CONTRAT', 'Contrat'), ('DIPLOME', 'Diplôme'), ('PERMIS', 'Permis'), ('AUTRE', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.salarie')),
            ],
        ),
    ]
