# Generated by Django 5.2.13 on 2026-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
