# Generated by Django 5.2.13 on 2026-08-07 01:29

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_numero'),
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_importes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_expiration',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('CNI', 'Carte nationale d’identité'), ('PASSEPORT', 'Passeport'), ('CONTRAT', 'Contrat'), ('DIPLOME', 'Diplôme'), ('PERMIS', 'Permis'), ('RIB', 'RIB'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('AUTRE', 'Autre')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['salarie', 'type_document'], name='documents_d_salarie_f69d24_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['salarie', 'archive'], name='documents_d_salarie_d3906e_idx'),
        ),
    ]
