# Generated by Django 5.2.13 on 2026-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_document_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('CNI', 'Carte nationale d’identité'), ('PASSEPORT', 'Passeport'), ('TITRE_SEJOUR', 'Titre de séjour'), ('CONTRAT', 'Contrat'), ('DIPLOME', 'Diplôme'), ('PERMIS', 'Permis'), ('RIB', 'RIB'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('AUTRE', 'Autre')], db_index=True, max_length=50),
        ),
    ]
