# Generated by Django 5.1.2 on 2026-04-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('type_journee', models.CharField(choices=[('BUREAU', 'Bureau'), ('TELETRAVAIL', 'Télétravail'), ('CONGE', 'Congé'), ('ABSENCE', 'Absence'), ('VACATION', 'Vacation'), ('FORMATION', 'Formation')], default='BUREAU', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='users.salarie')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('salarie', 'date')},
            },
        ),
    ]
