# Generated by Django 5.2.13 on 2026-08-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('users', '0003_alter_salarie_options_alter_salarie_email_personnel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='type_journee',
            field=models.CharField(choices=[('BUREAU', 'Bureau'), ('TELETRAVAIL', 'Télétravail'), ('CONGE', 'Congé'), ('ABSENCE', 'Absence'), ('VACATION', 'Vacation'), ('FORMATION', 'Formation')], db_index=True, default='BUREAU', max_length=20),
        ),
        migrations.AddIndex(
            model_name='planning',
            index=models.Index(fields=['salarie', 'date'], name='planning_pl_salarie_3e1c76_idx'),
        ),
        migrations.AddIndex(
            model_name='planning',
            index=models.Index(fields=['type_journee', 'date'], name='planning_pl_type_jo_1ca9e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.UniqueConstraint(fields=('salarie', 'date'), name='unique_planning_salarie_date'),
        ),
    ]
